architect:
  - aliceice

docker:
  image: "slucky31/javafx"

install:
  - "java -version"
  - "mvn --version"
  - "mvn clean install -DskipTests"

merge:
  script:
    - "mvn clean verify -Pcode-quality"

release:
  script:
    - "mvn versions:set \"-DnewVersion=${tag}\""
    - "mvn clean verify -Pcode-quality"
    - "git commit -am \"${tag}\""

